sigmah/src/main/java/org/sigmah/shared/dto/EntityDTO.java
/*
 * All Sigmah code is released under the GNU General Public License v3
 * See COPYRIGHT.txt and LICENSE.txt.
 */

package org.sigmah.shared.dto;

import com.extjs.gxt.ui.client.data.ModelData;

/**
 *
 * A data transfer object with a one-to-one relationship with
 * a JPA @Entity.
 *
 * @author Alex Bertram
 */
public interface EntityDTO extends DTO, ModelData {

    /**
     * @return the corresponding entity's @Id
     */
    public int getId();

    /**
     * @return the entity's JPA name
     */
    public String getEntityName();
}

sigmah/src/main/java/org/sigmah/server/endpoint/wfs/WfsServlet.java
/*
 * All Sigmah code is released under the GNU General Public License v3
 * See COPYRIGHT.txt and LICENSE.txt.
 */

package org.sigmah.server.endpoint.wfs;

import com.google.inject.Inject;
import com.google.inject.Injector;
import com.google.inject.Singleton;
import freemarker.template.Configuration;
import freemarker.template.Template;
import freemarker.template.TemplateException;

import org.sigmah.shared.domain.Activity;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

import javax.persistence.EntityManager;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import java.io.IOException;
import java.util.*;

/**
 *
 * An implementation of the Web Feature Service (WFS) Specification that allows
 * access to ActivityInfo directly from ArcGIS and other GIS software.
 *
 * This implementation relies heavily on FreeMarker, see /war/ftl/wfs for the
 * response templates.
 *
 * @author Alex Bertram
 */
@Singleton
public class WfsServlet extends HttpServlet {

    private final Injector injector;
    private final Configuration templateCfg;

    @Inject
    public WfsServlet(Injector injector, Configuration templateCfg) {
        this.injector = injector;
        this.templateCfg = templateCfg;
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse response)
            throws ServletException, IOException {

        response.setCharacterEncoding("UTF-8");

        this.log("WFS Get request: " + req.getQueryString());

        try {

            String requestType = req.getParameter("REQUEST");

            if(req.getQueryString() == null || "GetCapabilities".equalsIgnoreCase(requestType)) {

                writeCapabilities(req, response);


            } else if("DescribeFeatureType".equalsIgnoreCase(requestType) ) {

                List<String> featureTypes = new ArrayList<String>();

                for(String typeName : req.getParameterValues("typeName")) {
                    featureTypes.add(typeName);
                }

                writeFeatureDescription(featureTypes, response);

            } else if("GetFeature".equalsIgnoreCase(requestType)) {

                String outputFormat = req.getParameter("OUTPUTFORMAT");
                String resultType = req.getParameter("RESULTTYPE");
                String maxFeatures = req.getParameter("MAXFEATURES");

                String propertyNameList = req.getParameter("PROPERTYNAME");


                String typeName = req.getParameter("TYPENAME");
                List<String> types = new ArrayList<String>();
                if(typeName != null) {
                    types.addAll(Arrays.asList(typeName.split(",")));
                }
                


            }
        } catch(Exception e) {
            writeException(e, response);
        }
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp)
            throws ServletException, IOException {

        resp.setCharacterEncoding("UTF-8");

        try {

            if("text/xml".equals(req.getContentType())) {

                Document document;
                DocumentBuilderFactory factory =
                        DocumentBuilderFactory.newInstance();
                try
                {

                    DocumentBuilder builder = factory.newDocumentBuilder();
                    document = builder.parse(req.getInputStream());

                }catch (SAXException sxe)
                {
                    Exception e = sxe;
                    if (sxe.getException() != null) {
                        e = sxe.getException();
                    }
                    e.printStackTrace();
                    return;
                } catch (ParserConfigurationException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                    return;
                }

                String requestType = document.getDocumentElement().getNodeName();

                if(requestType.equals("GetCapabilities")) {

                    writeCapabilities(req, resp);


                } else if(requestType.equals("DescribeFeatureType")) {
                    List<String> featureTypes = new ArrayList<String>();
                    NodeList elements = document.getElementsByTagName("TypeName");

                    for(int i = 0; i!=elements.getLength(); ++i) {
                        featureTypes.add(elements.item(i).getTextContent());
                    }

                    writeFeatureDescription(featureTypes, resp);

                } else if(requestType.equals("GetFeatures")) {

                    getFeatures(document, resp);

                }

            }
        }catch(Exception e) {
            writeException(e, resp);
        }

    }



    protected void writeCapabilities( HttpServletRequest request, HttpServletResponse response) throws IOException, TemplateException {

        EntityManager em = injector.getInstance(EntityManager.class);

        Capabilities capabilities = new Capabilities();
        capabilities.setPostUrl("http://" + request.getServerName() + ":" + request.getServerPort() +
                request.getRequestURI());
        capabilities.setGetUrl(capabilities.getPostUrl() + "?");
        capabilities.setActivities(em.createQuery("select a from Activity a").getResultList());

        Template tpl = templateCfg.getTemplate("wfs/Capabilities.ftl");

        response.setContentType("text/xml");
        response.setCharacterEncoding("UTF-8");
        tpl.process(capabilities, response.getWriter());
    }

    protected void writeFeatureDescription(List<String> featureTypes, HttpServletResponse response) throws IOException, TemplateException {

        EntityManager em = injector.getInstance(EntityManager.class);
        List<Activity> activities = new ArrayList<Activity>();

        for(String name : featureTypes) {
            if(name.startsWith("activity")) {
                int activityId = Integer.parseInt(name.substring("activity".length()));
                activities.add(em.find(Activity.class, activityId ));
            }
        }

        Map<String, Object> model = new HashMap<String, Object>();
        model.put("activities", activities);

        Template tpl = templateCfg.getTemplate("wfs/FeatureType.ftl");

        response.setContentType("text/xml");
        response.setCharacterEncoding("UTF-8");
        tpl.process(model, response.getWriter());
    }

    private void getFeatures(Document document, HttpServletResponse resp) {

        Element reqElement = document.getDocumentElement();

        boolean countOnly = "hits".equals(reqElement.getAttribute("resultType"));

    }

    private void writeException(Exception e, HttpServletResponse response) {


        response.setContentType("text/plain");
        try {
            e.printStackTrace(response.getWriter());
        } catch (IOException e1) {

        }
    }


}

sigmah/src/main/webapp/ftl/wfs/Capabilities.ftl
<?xml version='1.0' encoding="UTF-8" ?>
<WFS_Capabilities
   version="1.0.0"
   updateSequence="0"
   xmlns="http://www.opengis.net/wfs"
   xmlns:ogc="http://www.opengis.net/ogc"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengeospatial.net//wfs/1.0.0/WFS-capabilities.xsd">

<Service>
  <Name>ActivityInfo WFS</Name>
  <Title>ActivityInfo WFS Server</Title>
  <Abstract>
      ActivityInfo WFS provides access to the geographic data in the ActivityInfo database.
  </Abstract>
  <Keywords>
    monitoring
    evaluation
    post-conflict
    humanitarian
  </Keywords>
  <OnlineResource>http://www.activityinfo.org</OnlineResource>
  <Fees>None</Fees>
  <AccessConstraints>None</AccessConstraints>
</Service>
<Capability>
  <Request>
    <GetCapabilities>
      <DCPType>
        <HTTP>
          <Get onlineResource="${getUrl}" />
        </HTTP>
      </DCPType>
      <DCPType>
        <HTTP>
          <Post onlineResource="${postUrl}" />
        </HTTP>
      </DCPType>
    </GetCapabilities>
    <DescribeFeatureType>
      <SchemaDescriptionLanguage>
        <XMLSCHEMA/>
        <SFE_XMLSCHEMA/>
      </SchemaDescriptionLanguage>
      <DCPType>
        <HTTP>
          <Get onlineResource="${getUrl}" />
        </HTTP>
      </DCPType>
      <DCPType>
        <HTTP>
          <Post onlineResource="${postUrl}" />
        </HTTP>
      </DCPType>
    </DescribeFeatureType>
    <GetFeature>
      <ResultFormat>
        <GML2/>
        <GML3/>
      </ResultFormat>
      <DCPType>
        <HTTP>
          <Get onlineResource="${getUrl}" />
        </HTTP>
      </DCPType>
      <DCPType>
        <HTTP>
          <Post onlineResource="${postUrl}" />
        </HTTP>
      </DCPType>
    </GetFeature>
  </Request>
</Capability>

<#list activities as activity>
<FeatureTypeList>
  <Operations>
    <Query/>
  </Operations>
    <FeatureType>
        <Name>activity${activity.id}</Name>
        <Title>${activity.database.name} - ${activity.name}</Title>
        <Abstract>
         <#if activity.database.fullName??>
            ${activity.database.fullName}
            <#else>
            ${activity.database.name}
            </#if>
            ${activity.name}
        </Abstract>
        <SRS>EPSG:4326</SRS>
        <LatLongBoundingBox minx="-180" miny="-90" maxx="180" maxy="90" />
    </FeatureType>
</FeatureTypeList>
</#list>

<ogc:Filter_Capabilities>
  <ogc:Spatial_Capabilities>
    <ogc:Spatial_Operators>

      <ogc:Intersect/>
      <ogc:DWithin/>
      <ogc:BBOX/>
    </ogc:Spatial_Operators>
  </ogc:Spatial_Capabilities>
  <ogc:Scalar_Capabilities>
    <ogc:Logical_Operators />
    <ogc:Comparison_Operators>
      <ogc:Simple_Comparisons />

      <ogc:Like />
      <ogc:Between />
    </ogc:Comparison_Operators>
  </ogc:Scalar_Capabilities>
</ogc:Filter_Capabilities>

</WFS_Capabilities>

sigmah/src/main/webapp/ftl/wfs/FeatureType.ftl
<?xml version='1.0' encoding="ISO-8859-1" ?>
<schema
        targetNamespace="http://www.activityinfo.org/schemas"
        xmlns:ai="http://www.activityinfo.org/schemas"
        xmlns:ogc="http://www.opengis.net/ogc"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:gml="http://www.opengis.net/gml"
        elementFormDefault="qualified" version="0.1" >

    <import namespace="http://www.opengis.net/gml"
            schemaLocation="http://schemas.opengeospatial.net//gml/2.1.2/feature.xsd" />

    <#list activities as activity>

    <element name="activity${activity.id}"
             type="ai:activity${activity.id}"
             substitutionGroup="gml:_Feature" />

    <complexType name="CBC_PYType">
        <complexContent>
            <extension base="gml:AbstractFeatureType">
                <sequence>

                    <element name="msGeometry" type="gml:GeometryPropertyType" minOccurs="0" maxOccurs="1"/>
                    <element name="id" type="integer"/>
                    <element name="partner" type="string"/>
                    <element name="location" type="string"/>
                    <element name="axe" type="string"/>
                    <element name="date1" type="date"/>
                    <element name="date2" type="date"/>
                    <#list activity.indicators as indicator>
                    <element name="indicator${indicator.id}" type="decimal"/>
                    </#list>
                    <#list activity.attributeGroups as group>
                        <#list group.attributes as attribute>
                            <element name="attribute${attribute.id}" type="string"/>
                        </#list>
                    </#list>
                    <#list activity.database.country.adminLevels as level>
                    <element name="${level.name}" type="string"/>
                    <element name="${level.name}_code" type="string"/>
                    </#list>
                    <element name="latitude" type="decimal"/>
                    <element name="longitude" type="decimal"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    </#list>

</schema>