sigmah/src/main/java/org/sigmah/shared/dto/UserDTO.java
package org.sigmah.shared.dto;

import java.util.Date;
import java.util.List;

import org.sigmah.shared.dto.profile.ProfileDTO;

import com.extjs.gxt.ui.client.data.BaseModelData;
/**
 * One-to-one DTO of the {@link org.sigmah.shared.domain.User} domain class.
 * 
 * @author nrebiai
 * 
 */
public class UserDTO extends BaseModelData implements EntityDTO {

	private static final long serialVersionUID = 5865780039352557006L;
	
    @Override
    public String getEntityName() {
        return "User";
    }

    @Override
    public int getId() {
        return (Integer) get("id");
    }

    public void setId(int id) {
        set("id", id);
    }

	
	public String getName() {
        return get("name");
    }

    public void setName(String name) {
        set("name", name);
    }
    
    public String getEmail() {
        return get("email");
    }

    public void setEmail(String email) {
    	set("email", email);
    }
    
    public String getFirstName() {
        return get("firstName");
    }

    public void setFirstName(String firstName) {
    	set("firstName", firstName);
    }
    
    public String getLocale() {
        return get("locale");
    }

    public void setLocale(String locale) {
    	set("locale", locale);
    }
    
    public OrgUnitDTO getOrgUnitWithProfiles() {
        return get("orgUnit");
    }

    public void setOrgUnitWithProfiles(OrgUnitDTO orgUnit) {
    	set("orgUnit", orgUnit);
    }
    
    public String getChangePasswordKey() {
        return get("pwdChangeKey");
    }

    public void setChangePasswordKey(String pwdChangeKey) {
    	set("pwdChangeKey", pwdChangeKey);
    }
    
    public Date getDateChangePasswordKeyIssued() {
        return get("pwdChangeDate");
    }

    public void setDateChangePasswordKeyIssued(Date pwdChangeDate) {
    	set("pwdChangeDate", pwdChangeDate);
    }
    
    public List<ProfileDTO> getProfilesDTO() {
    	return get("profilesDTO");
    }
    
    public void setProfilesDTO(List<ProfileDTO> profiles) {
        set("profilesDTO", profiles);
    }

    public String getCompleteName() {
        return get("cname");
    }

    public void setCompleteName(String cname) {
        set("cname", cname);
    }
    
    public void setIdd(int id){
    	set("idd", id);
    }
    
    public int getIdd(){
    	return (Integer) get("idd");
    }
    
    public void setActive(boolean isActive){
    	set("active", isActive);
    }
    
    public boolean getActive(){
    	Boolean isActive = (Boolean) get("active");
    	return isActive == null ? true : isActive;
    }

}

sigmah/src/main/java/org/sigmah/server/bootstrap/ConfirmInviteController.java
/*
 * All Sigmah code is released under the GNU General Public License v3
 * See COPYRIGHT.txt and LICENSE.txt.
 */

package org.sigmah.server.bootstrap;

import com.google.inject.Inject;
import com.google.inject.Injector;
import com.google.inject.Singleton;
import freemarker.template.Configuration;
import org.sigmah.server.Cookies;
import org.sigmah.server.auth.impl.PasswordHelper;
import org.sigmah.server.bootstrap.exception.IncompleteFormException;
import org.sigmah.server.bootstrap.exception.InvalidKeyException;
import org.sigmah.server.bootstrap.model.ConfirmInvitePageModel;
import org.sigmah.server.bootstrap.model.InvalidInvitePageModel;
import org.sigmah.server.dao.Transactional;
import org.sigmah.server.domain.Authentication;
import org.sigmah.server.util.logging.LogException;
import org.sigmah.shared.dao.UserDAO;
import org.sigmah.shared.domain.User;

import javax.persistence.NoResultException;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

import static org.sigmah.server.util.StringUtil.isEmpty;


@Singleton
public class ConfirmInviteController extends AbstractController {
    public static final String ENDPOINT = "confirm";

    @Inject
    public ConfirmInviteController(Injector injector, Configuration templateCfg) {
        super(injector, templateCfg);
    }

    @Override
    @LogException(emailAlert = true)
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        try {
            User user = findUserByKey(req.getQueryString());
            ConfirmInvitePageModel model = new ConfirmInvitePageModel(user);

            writeView(resp, model);

        } catch (InvalidKeyException e) {
            writeView(resp, new InvalidInvitePageModel());
        }
    }

    @Override
    @LogException(emailAlert = true)
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

        User user = null;
        try {
            user = findUserByKey(req.getParameter("key"));
        } catch (InvalidKeyException e) {
            writeView(resp, new InvalidInvitePageModel());
        }

        try {
            processForm(req, resp, user);
            resp.sendRedirect(HostController.ENDPOINT);

        } catch (IncompleteFormException e) {
            writeView(resp, ConfirmInvitePageModel.incompleteForm(user));
        }
    }

    @Transactional
    private void processForm(HttpServletRequest req, HttpServletResponse resp, User user) {
        confirmUserProfile(req, user);

        Authentication auth = createNewAuthToken(user);
        Cookies.addAuthCookie(resp, auth, false);
    }

    @Transactional
    protected User findUserByKey(String key) throws InvalidKeyException {
        try {
            if (isEmpty(key)) {
                throw new InvalidKeyException();
            }

            UserDAO userDAO = injector.getInstance(UserDAO.class);
            return userDAO.findUserByChangePasswordKey(key);

        } catch (NoResultException e) {
            throw new InvalidKeyException();
        }
    }

    @Transactional
    private void confirmUserProfile(HttpServletRequest request, User user) throws IncompleteFormException {
        String name = getRequiredParameter(request, "name");
        String locale = getRequiredParameter(request, "locale");
        String password = getRequiredParameter(request, "password");

        user.setName(name);
        user.setLocale(locale);
         
        user.setHashedPassword(PasswordHelper.hashPassword(password));
        user.clearChangePasswordKey();
        user.setNewUser(false);
    }

    private String getRequiredParameter(HttpServletRequest request, String name) {
        String value = request.getParameter(name);
        if (isEmpty(value)) {
            throw new IncompleteFormException();
        }

        return value;
    }
}

sigmah/src/main/java/org/sigmah/server/bootstrap/HostController.java
/*
 * All Sigmah code is released under the GNU General Public License v3
 * See COPYRIGHT.txt and LICENSE.txt.
 */

package org.sigmah.server.bootstrap;

import com.google.inject.Inject;
import com.google.inject.Injector;
import com.google.inject.Singleton;
import freemarker.template.Configuration;
import org.sigmah.server.Cookies;
import org.sigmah.server.bootstrap.exception.NoValidAuthentication;
import org.sigmah.server.bootstrap.model.HostPageModel;
import org.sigmah.server.dao.AuthenticationDAO;
import org.sigmah.server.dao.Transactional;
import org.sigmah.server.domain.Authentication;
import org.sigmah.server.util.logging.LogException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.Properties;

import static org.sigmah.server.util.StringUtil.isEmpty;

@Singleton
public class HostController extends AbstractController {
    public static final String ENDPOINT = "";

    private final Properties config;

    @Inject
    public HostController(Injector injector, Configuration templateCfg, Properties config) {
        super(injector, templateCfg);
        this.config = config;
    }

    @Override
    @LogException(emailAlert = true)
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

        if("Sigmah".equals(config.getProperty("default.interface"))) {
            resp.sendRedirect("Sigmah/");
            return;
        }

        if (requestIsFromIE6OnPort80(req)) {
            redirectToPort(req, resp, 8080);
            return;
        }

        try {
            Authentication auth = getAuthentication(req);
            if("true".equals(req.getParameter("redirect"))) {
                Cookies.addAuthCookie(resp, auth, false);
                resp.sendRedirect(HostController.ENDPOINT);
            } else {
                writeView(resp, new HostPageModel(auth, computeAppUrl(req)));
            }
        } catch (NoValidAuthentication noValidAuthentication) {
            resp.sendRedirect(LoginController.ENDPOINT + parseUrlSuffix(req));
        }
    }

    @Transactional
    protected Authentication getAuthentication(HttpServletRequest request) throws NoValidAuthentication {
        String authToken = request.getParameter("auth");
        if(isEmpty(authToken)) {
            authToken = getCookie(request, Cookies.AUTH_TOKEN_COOKIE);
        }
        if (isEmpty(authToken)) {
            throw new NoValidAuthentication();
        }

        AuthenticationDAO authDAO = injector.getInstance(AuthenticationDAO.class);
        Authentication auth = authDAO.findById(authToken);

        if (auth == null) {
            throw new NoValidAuthentication();
        }

        return auth;
    }

    private boolean requestIsFromIE6OnPort80(HttpServletRequest request) {
        return request.getServerPort() == 80 &&
                request.getServerName() != null &&
                request.getServerName().endsWith("activityinfo.org") &&
                !"80".equals(request.getParameter("port")) &&
                request.getHeader("User-Agent") != null &&
                request.getHeader("User-Agent").indexOf("MSIE 6.0") != -1;
    }

    private void redirectToPort(HttpServletRequest request, HttpServletResponse response, int port) throws IOException {
        // there is some sort of enormous problem with IE6 and something
        // to do with the tomcat isapi redirector.
        // When *some* IE6 users access the page through the tomcat redirect,
        // IE6 hangs when images are dynamically added to the page
        // This does not happen when accessed directly through the tomcat server.
        //
        // Until we can figure out what the heck is going on and "fix" the redirector,
        // we are just going to redirect all IE6 users to port 8080


        StringBuilder directUrl = new StringBuilder();
        directUrl.append("http://");
        directUrl.append(request.getServerName()).append(":8080");
        directUrl.append(request.getRequestURI());
        if (request.getQueryString() != null && request.getQueryString().length() != 0) {
            directUrl.append("?").append(request.getQueryString());
        }

        String bookmark = parseUrlSuffix(request);
        if (bookmark != null && bookmark.length() != 0) {
            directUrl.append("#").append(bookmark);
        }

        response.sendRedirect(directUrl.toString());
    }

    /**
     * @return  The url used for the desktop shortcut
     */
    private String computeAppUrl(HttpServletRequest request) {
        StringBuilder url = new StringBuilder();
        url.append("http://");
        url.append(request.getServerName());
        if(request.getServerPort() != 80) {
           url.append(":").append(request.getServerPort());
        }
        url.append(request.getRequestURI());
        return url.toString();
    }
}

sigmah/src/main/java/org/sigmah/server/bootstrap/LoginController.java
/*
 * All Sigmah code is released under the GNU General Public License v3
 * See COPYRIGHT.txt and LICENSE.txt.
 */

package org.sigmah.server.bootstrap;

import com.google.inject.Inject;
import com.google.inject.Injector;
import com.google.inject.Singleton;
import freemarker.template.Configuration;

import org.sigmah.server.auth.Authenticator;
import org.sigmah.server.bootstrap.model.LoginPageModel;
import org.sigmah.server.util.logging.LogException;
import org.sigmah.shared.domain.User;
import org.sigmah.shared.exception.InvalidLoginException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

@Singleton
public class LoginController extends AbstractController {
    public static final String ENDPOINT = "login";

    @Inject
    public LoginController(Injector injector, Configuration templateCfg) {
        super(injector, templateCfg);
    }

    @Override
    @LogException(emailAlert = true)
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        writeView(resp, new LoginPageModel(parseUrlSuffix(req)));
    }

    @Override
    @LogException(emailAlert = true)
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        try {
            User user = findUserByEmail(req.getParameter("email"));
            checkPassword(req.getParameter("password"), user);

            boolean rememberLogin = "true".equals(req.getParameter("remember"));
            createAuthCookie(req, resp, user, rememberLogin);

            resp.sendRedirect(HostController.ENDPOINT + urlSuffix(req));

        } catch (InvalidLoginException e) {
            writeView(resp, LoginPageModel.unsuccessful(urlSuffix(req)));
        }
    }

    protected void checkPassword(String password, User user) throws InvalidLoginException {
        Authenticator authenticator = injector.getInstance(Authenticator.class);
        if (!authenticator.check(user, password)) {
            throw new InvalidLoginException();
        }
    }

    protected String urlSuffix(HttpServletRequest req) {
        String suffix = req.getParameter("urlSuffix");
        return suffix == null ? "" : suffix;
    }

}

sigmah/src/main/resources/template/page/ConfirmInvite.ftl
<#-- @ftlvariable name="" type="org.sigmah.server.bootstrap.model.ConfirmInvitePageModel" -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
    <meta http-equiv="Cache-Control" content="no-cache"/>
    <meta name="description" content="ActivityInfo est la solution ">
    <title>ActivityInfo - Welcome</title>
</head>
<body>

<h1>Welcome to ActivityInfo</h1>

<p>Before we get started, let's set up your account. Confirm your name and preferred language,
    and then choose a password.</p>

<form name="Form1" method="post" id="Form1" action="confirm" method="post">
    <input type="hidden" name="key" value="${user.changePasswordKey}"></input>
    <table>
        <tr>
            <td>Confirm your name:</td>
            <td><input name="name" value="${user.name}"></td>
        </tr>
        <tr>
            <td>Confirm your preferred language:</td>
            <td>
                <select name="locale">
                    <option value="en">English</option>
                    <option value="fr">French / Français</option>
                </select>
            </td>
        </tr>
        <tr>
            <td>Choose a password:</td>
            <td><input name="password" type="password"></td>
        </tr>
        <tr>
            <td>Confirm your password:</td>
            <td><input name="password2" type="password"></td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td><input type="submit" value="Continue"></td>
        </tr>
    </table>
</form>
</body>
</html>

sigmah/src/main/resources/template/page/Host.ftl
<#-- @ftlvariable name="" type="org.sigmah.server.bootstrap.model.HostPageModel" -->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html manifest="ActivityInfo/html5.manifest">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="application-name" content="ActivityInfo"/>
    <meta name="description" content="ActivityInfo"/>
    <meta name="application-url" content="${appUrl}"/>
    <link rel="icon" href="ActivityInfo/desktopicons/16x16.png" sizes="16x16"/>
    <link rel="icon" href="ActivityInfo/desktopicons/32x32.png" sizes="32x32"/>
    <link rel="icon" href="ActivityInfo/desktopicons/48x48.png" sizes="48x48"/>
    <link rel="icon" href="ActivityInfo/desktopicons/64x64.png" sizes="64x64"/>
    <link rel="icon" href="ActivityInfo/desktopicons/128x128.png" sizes="128x128"/>

    <title>ActivityInfo</title>
    <style type="text/css">
        #loading-box {
            position: absolute;
            left: 45%;
            top: 40%;
            padding: 2px;
            margin-left: -45px;
            z-index: 20001;
            border: 1px solid #ccc;
        }

        #loading-box .loading-indicator {
            background: #eef;
            font: bold 13px tahoma, arial, helvetica;
            padding: 10px;
            margin: 0;
            height: auto;
            color: #444;
        }

        #loading-box .loading-indicator img {
            margin-right: 8px;
            float: left;
            vertical-align: top;
        }

        #loading-msg {
            font: normal 10px tahoma, arial, sans-serif;
        }

        #loading-options {
            position: absolute;
            right: 10px;
            bottom: 10px;
            font: normal 13px tahoma, arial, sans-serif;
            text-align: right;
        }
        <#include "Application.css">
    </style>
    <script type="text/javascript">
        var UserInfo = {
            userId: ${auth.user.id},
            authToken: "${auth.id}",
            email: "${auth.user.email}"
        };
        var GoogleMapsAPI = {
            key: "ABQIAAAAHxDe2DM8fTqR3KT6JA3uSxQowpcadhvcZvF-AZHbBConS0qRQRSyDoOLQrw76pJeJNUXt2g-yC8FAg"
        };
        var VersionInfo = {
            revision: ${activityinfo.revision}
        };
        <#if offline == true>
        function disableOffline() {
            document.cookie = "offline=false;expires=Thu, 01-Jan-1970 00:00:01 GMT";
            window.location.reload();
        }
        </#if>
    </script>

    <script language='javascript' src='ActivityInfo/gxt/flash/swfobject.js'></script>
    <script type="text/javascript" language="javascript" src="ActivityInfo/ActivityInfo.nocache.js"></script>
    <link rel="stylesheet" type="text/css" href="ActivityInfo/gxt/css/gxt-all.css"/>
    <link rel="stylesheet" type="text/css" href="report.css"/>

</head>
<body>
<div id="loading">
    <div id="loading-box">
        <div class="loading-indicator">
            <img src="ActivityInfo/gxt/images/default/shared/large-loading.gif" alt=""/>
            ActivityInfo r${activityinfo.revision}<br/>
            <span id="loading-msg">Chargement en cours...</span>

        </div>
    </div>
<#if offline == true>
    <div id="loading-options">
        <a href="javascript:disableOffline()">Charger avec mode hors connexion desactiver</a>
    </div>
</#if>
</div>
<iframe src="javascript:''" id="__gwt_historyFrame" tabIndex='-1'
        style="position:absolute;width:0;height:0;border:0"></iframe>
<iframe src="javascript:''" id="_downloadFrame" name="_downloadFrame" tabIndex='-1'
        style="position:absolute;width:0;height:0;border:0"></iframe>
<script type="text/javascript">
    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
    try {
        var pageTracker = _gat._getTracker("UA-11567120-1");
        pageTracker._trackPageview("/login/success");
    } catch(err) {
    }</script>
</body>
</html>

sigmah/src/main/resources/template/page/InvalidInvite.ftl
<html>
<head>
    <title>ActivityInfo - Invalid Key</title>
</head>

<body>

<h1>Invalid Invite</h1>

<p>This invitation is invalid or has already been used. You can access the login
    page from <a href="login">here</a></p>

</body>